server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: quiz-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: ${SHOW_SQL:true}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/doping}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

redis:
  redisHost: ${REDIS_HOST:localhost}
  redisPort: ${REDIS_PORT:6379}